routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/website', 'HomeController@website')->name('website');
Route::get('/addToCart/{product_id}', 'HomeController@addToCart')->name('addToCart');
Route::get('/myCart', 'HomeController@myCart')->name('myCart');
Route::get('/deleteCart/{id}', 'HomeController@deleteCart');

Route::group(['prefix'=>'admin','middleware'=>['auth']],function(){
	Route::redirect('/','login');
	Route::get('/home', 'HomeController@index')->name('admin.home');
	Route::resource('category','CategoryController');
  	Route::resource('product','ProductController');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    protected $table = "products";

    protected $fillable = [
    	'category_id',
    	'name',
    	'description',
    	'feature_image',
    	'price',
    ];

    public function category(){
      return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Category;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('id','DESC')->get();
        return view('product.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('product.add',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,
            [
              'name'=>'required',
              'category_id'=>'required',
              'description'=>'required',
              'price'=>'required',
              'feature_image'=>'required',
            ],
            [
                "category_id.required"=>"Please Select Category",
                "feature_image.required"=>"Please Upload Feature Image",
            ]
        );

        $request_array = array();
        $request_array = $request->all();

        $featured_imageName = '';
        if($request->feature_image != null)
        {
            $imageName = 'feature_image_'.$request->feature_image->getClientOriginalName();

            $request->file('feature_image')->move(base_path() . '/public/storage/images/', $imageName);

            $featured_imageName = $imageName;

            $request_array['feature_image'] = $imageName;
        }
        else{
          $request_array['feature_image'] = '';
        }
        Product::create($request_array);

        return redirect()->route('product.index')->with('message','Product added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $categories = Category::all();
        return view('product.edit',compact('product','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $this->validate($request,
            [
              'name'=>'required',
              'category_id'=>'required',
              'description'=>'required',
              'price'=>'required',
            ],
            [
                "category_id.required"=>"Please Select Category",
            ]
        );

        $request_array = array();
        $request_array = $request->all();   

        $featured_imageName = '';
        if($request->feature_image != null)
        {
            $imageName = 'feature_image_'.$request->feature_image->getClientOriginalName();

            $request->file('feature_image')->move(base_path() . '/public/storage/images/', $imageName);

            $featured_imageName = $imageName;

            $request_array['feature_image'] = $imageName;
        }
        else{
          $request_array['feature_image'] = $product->feature_image;
        }
        $product->update($request_array);

        return redirect()->route('product.index')->with('message','Product updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        //
    }
}

resources/views/product/add.blade.php
 @extends('layouts.masters')
 @section('title')
    Add Product
 @endsection
 @section('page-content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>Product</h1>
            <ol class="breadcrumb">
                <li><a ><i class="fa fa-home"></i> Home</a></li>
                <li class="active">Add Product</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Add Product</h3>
                        </div>
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('product.store') }}" method="post" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            <div class="box-body">
                                <div class="row">
                                    <div class="col-md-6 col-sm-8 col-xs-8">
                                        <div class="form-group">
                                            <label>NAME</label>
                                            <input type="text" class="form-control" id="name" placeholder="Name" name="name" value="{{ old('name') }}" required>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-8 col-xs-8">
                                        <div class="form-group">
                                            <label>Category</label>
                                            <select id="selectbox" data-selected="" name="category_id" class="form-control">
                                                <option value="" selected="selected" disabled="disabled"> Select Category</option>
                                                @foreach($categories as $category)
                                                <option value="{{$category->id}}">{{$category->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-8 col-xs-8">
                                        <div class="form-group">
                                            <label>Price</label>
                                            <input type="number" class="form-control" id="price" placeholder="Price" name="price" value="{{ old('price') }}" required>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-8 col-xs-8">
                                        <div class="form-group">
                                            <label>Description</label>
                                            <textarea name="description" placeholder="Description" class="form-control" style="resize: vertical;height: auto" rows="5" required></textarea>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <label>Feature Image</label>
                                                    <div class="upload-image">
                                                        <input type='file' class="imgInp" data-id='img3'  name="feature_image" onchange="document.getElementById('feature_image_show').src =window.URL.createObjectURL(this.files[0])" accept="image/*"/>
                                                    </div>
                                                </div>
                                                <div class="col-md-12" style="margin-top: 30px">
                                                    <img id="img3" src=""  alt="" height="100" id="feature_image_show" style="width: 300px;height: 300px" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="box-footer" align="center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>

                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>

    </div>
    <!-- //Content Wrapper -->
@endsection

@section('page-scripts')
    
@endsection

resources/views/product/edit.blade.php
 @extends('layouts.masters')
 @section('title')
    Edit Product
 @endsection
 @section('page-content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>Product</h1>
            <ol class="breadcrumb">
                <li><a ><i class="fa fa-home"></i> Home</a></li>
                <li class="active">Edit Product</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Edit Product</h3>
                        </div>
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('product.update',$product->id) }}" method="post" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}
                            <div class="box-body">
                                <div class="row">
                                    <div class="col-md-6 col-sm-8 col-xs-8">
                                        <div class="form-group">
                                            <label>NAME</label>
                                            <input type="text" class="form-control" id="name" placeholder="Name" name="name" value="{{ $product->name }}" required>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-8 col-xs-8">
                                        <div class="form-group">
                                            <label>Category</label>
                                            <select id="selectbox" data-selected="" name="category_id" class="form-control">
                                                <option value="" selected="selected" disabled="disabled"> Select Category</option>
                                                @foreach($categories as $category)
                                                    <option value="{{$category->id}}" @if($category->id == $product->category_id) selected @endif>{{$category->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-8 col-xs-8">
                                        <div class="form-group">
                                            <label>Price</label>
                                            <input type="number" class="form-control" id="price" placeholder="Price" name="price" value="{{ $product->price }}" required>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-8 col-xs-8">
                                        <div class="form-group">
                                            <label>Description</label>
                                            <textarea name="description" placeholder="Description" class="form-control" style="resize: vertical;height: auto" rows="5" required>{{$product->description}}</textarea>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <label>Feature Image</label>
                                                    <div class="upload-image">
                                                        <input type='file' class="imgInp" data-id='img3'  name="feature_image" onchange="document.getElementById('feature_image_show').src =window.URL.createObjectURL(this.files[0])" accept="image/*"/>
                                                    </div>
                                                </div>
                                                <div class="col-md-12" style="margin-top: 30px">
                                                    <img id="img3" src="{{ asset('storage/images/'.$product->feature_image) }}"  alt="" height="100" id="feature_image_show" style="width: 300px;height: 300px" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="box-footer" align="center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>

                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>

    </div>
    <!-- //Content Wrapper -->
@endsection

@section('page-scripts')
    
@endsection

resources/views/product/index.blade.php
@extends('layouts.masters')
@section('title')
All Products
@endsection
 @section('page-content')

<div class="content-wrapper" style="min-height: 916px;">
   <!-- Content Header (Page header) -->
   <section class="content-header">
       <h1>Products</h1>
       <ol class="breadcrumb">
           <li><a ><i class="fa fa-home"></i> Home</a></li>
           <li class="active">Products</li>
       </ol>
   </section>
   <!-- Main content -->
   <section class="content">
       <div class="row">
           <div class="col-xs-12">
             @if(Session::has('message'))
             <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
             @endif
               <div class="box">
                   <div class="box-header">
                       <h3 class="box-title">Products List</h3>
                   </div>
                   <!-- /.box-header -->
                   <div class="box-body">
                       <div class="row">
                           <div class="col-sm-12">
                               <table id="example1" class="table table-bordered table-striped" style="width: 100%">
                                   <thead>
                                       <tr role="row" style="text-align: center;">
                                           <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending" style="width: 50px;">
                                             #
                                           </th>
                                           <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending" style="width: 142px;">
                                             Product Name
                                           </th>
                                           <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending" style="width: 142px;">
                                             Category
                                           </th>
                                           <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending" style="width: 142px;">
                                             Price
                                           </th>
                                           <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" style="width: 161px;">
                                             Action
                                           </th>
                                       </tr>
                                   </thead>
                                   <tbody>
                                       @foreach($products as $key => $product)

                                           <tr role="row" class="odd">
                                               <td class="sorting_1">{{++$key}}</td>
                                               <td class="sorting_1">{{$product->name}}</td>
                                               <td class="sorting_1">{{$product->category->name}}</td>
                                               <td class="sorting_1">{{$product->price}}</td>
                                               <td style="display:flex;">
                                                   <a href="{{route('product.edit',['id'=>$product->id])}}" style="margin-right: 15px;margin-top:2px;">
                                                       <i class="fa fa-edit" aria-hidden="true"></i>
                                                   </a>
                                                   <form method="POST" action="{{route('product.destroy',$product->id)}}">
                                                     {{csrf_field()}}
                                                     {{method_field('DELETE')}}
                                                     <button type="submit" data-toggle="tooltip" data-placement="top" title="Delete" style="background:transparent;border:none;"><i class="fa fa-trash" aria-hidden="true" style="color:red;"></i></button>
                                                   </form>
                                               </td>
                                           </tr>
                                       @endforeach
                                   </tbody>
                               </table>
                           </div>
                       </div>
                   </div>
                   <!-- /.box-body -->
               </div>
               <!-- /.box -->
           </div>
           <!-- /.col -->
       </div>
       <!-- /.row -->
   </section>
   <!-- /.content -->
</div>
@endsection