routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/website', 'HomeController@website')->name('website');
Route::get('/addToCart/{product_id}', 'HomeController@addToCart')->name('addToCart');
Route::get('/myCart', 'HomeController@myCart')->name('myCart');
Route::get('/deleteCart/{id}', 'HomeController@deleteCart');

Route::group(['prefix'=>'admin','middleware'=>['auth']],function(){
	Route::redirect('/','login');
	Route::get('/home', 'HomeController@index')->name('admin.home');
	Route::resource('category','CategoryController');
  	Route::resource('product','ProductController');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';

    protected $fillable = ['name'];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('id','DESC')->get();
        return view('category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('category.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
          'name'=>'required'
        ]);
        Category::create($request->all());
        return redirect()->route('category.index')->with('message','Category added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('category.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->validate($request,[
            'name'=>'required'
          ]);
          $category->update($request->all());
          return redirect()->route('category.index')->with('message','Category updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        if(Product::where('category_id',$category->id)->exists() == true){
          return redirect()->route('category.index')->with('message','Category Associated with a product. Cannot be deleted');
        }
        $category->delete();
        return redirect()->route('category.index')->with('message','Category deleted Successfully');
    }
}

resources/views/category/add.blade.php
 @extends('layouts.masters')
 @section('title')
 Add Category
 @endsection
 @section('page-content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>Category</h1>
            <ol class="breadcrumb">
                <li><a ><i class="fa fa-home"></i> Home</a></li>
                <li class="active">Add Category</li>
            </ol>
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Add Category</h3>
                        </div>
                        @if ($errors->any())
                         <div class="alert alert-danger">
                            <ul>
                               @foreach ($errors->all() as $error)
                               <li>{{ $error }}</li>
                               @endforeach
                            </ul>
                         </div>
                         @endif
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" action="{{ route('category.store') }}" method="post" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            <div class="box-body">
                                <div class="row">
                                    <div class="col-md-5 col-sm-8 col-xs-8">
                                        <div class="form-group">
                                            <label>CATEGORY NAME</label>
                                            <input type="text" class="form-control" id="name" placeholder="Enter Category Name" name="name" value="{{ old('name') }}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>
    <!-- //Content Wrapper -->
@endsection
@section('page-scripts')
@endsection

resources/views/category/edit.blade.php
@extends('layouts.masters')
@section('title')
Edit Category
@endsection
@section('page-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>Category</h1>
    <ol class="breadcrumb">
      <li><a ><i class="fa fa-home"></i> Home</a></li>
      <li class="active">Edit Category</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
    <div class="row">
      <!-- left column -->
      <div class="col-md-12 col-sm-12 col-xs-12">
        <!-- general form elements -->
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Edit Category</h3>
          </div>
          @if ($errors->any())
          <div class="alert alert-danger">
            <ul>
              @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
              @endforeach
            </ul>
          </div>
          @endif
          <!-- /.box-header -->
          <!-- form start -->
          <form role="form" action="{{ route('category.update',$category->id) }}" method="post">
            {{ csrf_field() }}
            {{ method_field('PUT')}}
            <div class="box-body">
              <div class="row">
                <div class="col-md-5 col-sm-8 col-xs-8">
                  <div class="form-group">
                    <label>CATEGORY NAME</label>
                    <input type="text" class="form-control" id="name" placeholder="Enter Category Name" name="name" value="{{ $category->name }}">
                  </div>
                </div>
              </div>
            </div>
            <br>
            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </form>
        </div>
        <!-- /.box -->
      </div>
    </div>
  </section>

</div>
<!-- //Content Wrapper -->
@endsection
@section('page-scripts')
@endsection

resources/views/category/index.blade.php
 @extends('layouts.masters')
 @section('title')
 All Categories
 @endsection
  @section('page-content')
<div class="content-wrapper" style="min-height: 916px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>Categories</h1>
        <ol class="breadcrumb">
            <li><a ><i class="fa fa-home"></i> Home</a></li>
            <li class="active">Categories</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
              @if(Session::has('message'))
              <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
              @endif
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Categories List</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example1" class="table table-bordered table-striped" style="width: 100%">
                                    <thead>
                                        <tr role="row" style="text-align: center;">
                                            <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending" style="width: 50px;">#</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending" style="width: 142px;">Category Name</th>

                                            <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" style="width: 161px;">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($categories as $key => $category)

                                            <tr role="row" class="odd">
                                                <td class="sorting_1">{{++$key}}</td>
                                                <td class="sorting_1">{{$category->name}}</td>
                                                <td style="display:flex;">
                                                    <a href="{{route('category.edit',['id'=>$category->id])}}" style="margin-right: 15px;margin-top:2px;">
                                                        <i class="fa fa-edit" aria-hidden="true"></i>
                                                    </a>
                                                    <form method="POST" action="{{route('category.destroy',$category->id)}}">
                                                      {{csrf_field()}}
                                                      {{method_field('DELETE')}}
                                                      <button type="submit" data-toggle="tooltip" data-placement="top" title="Delete" style="background:transparent;border:none;"><i class="fa fa-trash" aria-hidden="true" style="color:red;"></i></button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
@endsection