routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/website', 'HomeController@website')->name('website');
Route::get('/addToCart/{product_id}', 'HomeController@addToCart')->name('addToCart');
Route::get('/myCart', 'HomeController@myCart')->name('myCart');
Route::get('/deleteCart/{id}', 'HomeController@deleteCart');

Route::group(['prefix'=>'admin','middleware'=>['auth']],function(){
	Route::redirect('/','login');
	Route::get('/home', 'HomeController@index')->name('admin.home');
	Route::resource('category','CategoryController');
  	Route::resource('product','ProductController');
});

resources/views/_partials/footer.blade.php
 <footer class="main-footer">
    <!-- <div class="pull-right hidden-xs">
      <b>Version</b> 2.4.0
    </div> -->
    <strong>Copyright &copy; 2019-2021 </strong> All rights
    reserved.
  </footer>

resources/views/_partials/link.blade.php
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/font-awesome.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/ionicons.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/dataTables.bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/jquery-jvectormap.css')}}">
    <link rel="stylesheet" href="{{asset('css/AdminLTE.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/_all-skins.min.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />

    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

resources/views/_partials/nav.blade.php
<aside class="main-sidebar">
    <section class="sidebar">
        <ul class="sidebar-menu" data-widget="tree">
            <li>
                <a href="{{route('admin.home')}}">
                    <i class="fa fa-home"></i> <span>Home</span>
                </a>
            </li>
            @php
                $category_array = array('admin/category/create','admin/category');
            @endphp
            <li class="treeview @if(in_array(Request::path(),$category_array)) active menu-open @endif">
                <a href="#">
                    <i class="fa fa-user"></i>
                    <span>Category</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="{{ Request::is('admin/category/create') ? 'active' : '' }}"><a href="{{ route('category.create') }}"><i class="fa fa-plus-circle"></i> Add</a></li>
                    <li class="{{ Request::is('admin/category') ? 'active' : '' }}"><a href="{{ route('category.index') }}"><i class="fa fa-list-ul"></i> View</a></li>
                </ul>
            </li>
            @php
                $product_array = array('admin/product/create','admin/product');
            @endphp
            <li class="treeview @if(in_array(Request::path(),$product_array)) active menu-open @endif">
                <a href="#">
                    <i class="fa fa-user"></i>
                    <span>Product</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="{{ Request::is('admin/product/create') ? 'active' : '' }}"><a href="{{ route('product.create') }}"><i class="fa fa-plus-circle"></i> Add Product</a></li>
                    <li class="{{ Request::is('admin/product') ? 'active' : '' }}"><a href="{{ route('product.index') }}"><i class="fa fa-list-ul"></i> View Products</a></li>
                </ul>
            </li>
        </ul>
    </section>
</aside>

resources/views/_partials/scripts.blade.php
    <script src="{{asset('js/jquery.min.js')}}"></script>
    <script src="{{asset('js/bootstrap.min.js')}}"></script>
    <script src="{{asset('js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('js/dataTables.bootstrap.min.js')}}"></script>
    <script src="{{asset('js/select2.full.min.js')}}"></script>
    <script src="{{asset('js/fastclick.js')}}"></script>
    <script src="{{asset('js/adminlte.min.js')}}"></script>
    <script src="{{asset('js/jquery.sparkline.min.js')}}"></script>
    <script src="{{asset('js/jquery-jvectormap-1.2.2.min.js')}}"></script>
    <script src="{{asset('js/jquery-jvectormap-world-mill-en.js')}}"></script>
    <script src="{{asset('js/jquery.slimscroll.min.js')}}"></script>
    <script src="{{asset('js/Chart.js')}}"></script>
    <script src="{{asset('js/demo.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
 






    <script>
        $(document).ready(function() {
            if (window.File && window.FileList && window.FileReader) 
            {
                $("#files").on("change", function(e) {
                    var files = e.target.files,
                    filesLength = files.length;
                    for (var i = 0; i < filesLength; i++) 
                    {
                        var f = files[i]
                        var fileReader = new FileReader();
                        fileReader.onload = (function(e) {
                        var file = e.target;
                            $("<span class=\"pip\">" +
                            "<img class=\"imageThumb\" src=\"" + e.target.result + "\" title=\"" + file.name + "\"/>" +
                            // "<br/><span class=\"remove\">Remove image</span>" +
                            "</span>").insertAfter("#files");
                            // $(".remove").click(function(){
                            //   $(this).parent(".pip").remove();
                            // });
                  
                            // Old code here
                            /*$("<img></img>", {
                                class: "imageThumb",
                                src: e.target.result,
                                title: file.name + " | Click to remove"
                            }).insertAfter("#files").click(function(){$(this).remove();});*/

                        });
                        fileReader.readAsDataURL(f);
                    }
                });
            } 
            else 
            {
                alert("Your browser doesn't support to File API")
            }

            $(function () {
                $('#example1').DataTable()
                $('#water_bill_table').DataTable()
                $('#example3').DataTable()
                $('#example4').DataTable({
                  'paging'      : true,
                  'lengthChange': false,
                  'searching'   : false,
                  'ordering'    : true,
                  'info'        : true,
                  'autoWidth'   : false
                })
            })


            // modal img edit

            function readURL(input) 
            {
                if (input.files && input.files[0]) 
                {
                    var reader = new FileReader();
                    reader.onload = function(e) {
                        $('#imagePreview').css('background-image', 'url('+e.target.result +')');
                        $('#imagePreview').hide();
                        $('#imagePreview').fadeIn(650);
                    }
                    reader.readAsDataURL(input.files[0]);
                }
            }
            $("#imageUpload").change(function() {
                readURL(this);
            });
        });
</script>

<script>

  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
  })
})
</script>

<script>
  $('#send').on('click',function(){
      var val = $('#myText').val();

      $('.append').append(`

          <div class="direct-chat-msg right">
          <div class="direct-chat-info clearfix">
          <span class="direct-chat-name pull-right">Sarah Bullock</span>
          <span class="direct-chat-timestamp pull-left">23 Jan 6:10 pm</span>
          </div>
          <!-- /.direct-chat-info -->
          <img class="direct-chat-img" src="img/user3-128x128.jpg" alt="message user image">
          <!-- /.direct-chat-img -->
          <div class="direct-chat-text">
          `+val+`
          </div>
          <!-- /.direct-chat-text -->
          </div>
          `)

      $('#myText').val('');
  });
</script>

<script>

 function ImageSetter(input,target) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            target.attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$(".imgInp").change(function(){
  var imgDiv=$(this).data('id');  
  imgDiv=$('#' + imgDiv);    
  ImageSetter(this,imgDiv);
});
</script>

<script>

  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
  })
});
    $(function () {
    $('#message').DataTable({
      'paging'      : true,
      'lengthChange': true,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
  })
});
</script>

resources/views/_partials/top.blade.php
<header class="main-header">

    <a href="index2.html" class="logo">
        <span class="logo-mini"><b>PM</b></span>
        <span class="logo-lg"><b>WeBuy Test</b></span>
    </a>

    <nav class="navbar navbar-static-top">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown messages-menu">
                    {{-- <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">12</span>
                    </a> --}}
                    <ul class="dropdown-menu">
                        <li class="header">You have 12 messages</li>
                        <li>
                            <ul class="menu">
                                <a href="#">
                                    <div class="pull-left">
                                        <img src="{{asset('images/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">
                                    </div>
                                    <h4>
										Support Team
										<small><i class="fa fa-clock-o"></i> 5 mins</small>
									</h4>
                                    <p>Why not buy a new awesome theme?</p>
                                </a>
                        </li>
                        <!-- end message -->
                        <li>
                            <a href="#">
                                <div class="pull-left">
                                    <img src="{{asset('images/img/user3-128x128.jpg')}}" class="img-circle" alt="User Image">
                                </div>
                                <h4>
												AdminLTE Design Team
												<small><i class="fa fa-clock-o"></i> 2 hours</small>
											</h4>
                                <p>Why not buy a new awesome theme?</p>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="pull-left">
                                    <img src="{{asset('images/img/user4-128x128.jpg')}}" class="img-circle" alt="User Image">
                                </div>
                                <h4>
												Developers
												<small><i class="fa fa-clock-o"></i> Today</small>
											</h4>
                                <p>Why not buy a new awesome theme?</p>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="pull-left">
                                    <img src="{{asset('images/img/user3-128x128.jpg')}}" class="img-circle" alt="User Image">
                                </div>
                                <h4>
												Sales Department
												<small><i class="fa fa-clock-o"></i> Yesterday</small>
											</h4>
                                <p>Why not buy a new awesome theme?</p>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="pull-left">
                                    <img src="{{asset('images/img/user4-128x128.jpg')}}" class="img-circle" alt="User Image">
                                </div>
                                <h4>
												Reviewers
												<small><i class="fa fa-clock-o"></i> 2 days</small>
											</h4>
                                <p>Why not buy a new awesome theme?</p>
                            </a>
                        </li>
                        </ul>
                </li>
                <li class="footer"><a href="#">See All Messages</a></li>
                </ul>
                </li>
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- <img src="{{asset('images/img/user2-160x160.jpg')}}" class="user-image" alt="User Image"> -->
                        <span class="hidden-xs">{{Auth::user()->name}}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <!-- <img src="{{asset('images/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image"> -->

                            <p>
                                {{Auth::user()->email}}
                                <!-- <small>Member since Jun. 2019</small> -->
                            </p>
                        </li>
                        <!-- Menu Body -->

                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                            <form id="logout-form" action="/logout" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>